### ISSUE TITLE
Calling "bootstrap" script will fail with an error with automake 1.15

### ISSUE THREAD

**Issue by happenpappen** [paperclip/talpa#6]
When calling the "bootstrap" script to create the needed files for compilation will fail with this error on a current system using automake 1.15:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --warnings=no-portability 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --warnings=no-portability
autoreconf: running: /usr/bin/autoheader --warnings=no-portability
autoreconf: running: automake --add-missing --copy --no-force --warnings=no-portability
automake: error: global options already processed
automake: Please contact <bug-automake@gnu.org>.
 at /usr/share/automake-1.15/Automake/Channels.pm line 662, <GEN0> line 77.
        Automake::Channels::msg("automake", "", "global options already processed") called at /usr/share/automake-1.15/Automake/ChannelDefs.pm line 212
        Automake::ChannelDefs::prog_error("global options already processed") called at /usr/share/automake-1.15/Automake/Options.pm line 421
        Automake::Options::process_global_option_list(HASH(0x30b2960), HASH(0x30b29c0), HASH(0x30b2a20)) called at /usr/bin/automake line 5337
        Automake::scan_autoconf_traces("configure.ac") called at /usr/bin/automake line 5437
        Automake::scan_autoconf_files() called at /usr/bin/automake line 8261
autoreconf: automake failed with exit status: 29

**Comment by paperclip** [comment]
Hi,

I've merged our current changes to paperclip/talpa master branch, which fixes automake 1.15 support (At least I can bootstrap on Ubuntu 16.04 with automake 1.15). But you might be best off following sophos/talpa perforce branch, which is where changes get pushed more frequently.

**Comment by happenpappen** [comment]
Hi,

thanks for your fast response. I had a look at the sophos/talpa perforce branch, but can't see the option to open an issue there. I would like to open one regarding compilation with kernel version 4.7.2 where it looks like the inode struct has changed and there is no member i_mutex anymore.

Kind regards,

Christoph
